### ISSUE TITLE
Windows 11 (Fixed)

### ISSUE THREAD

**Issue by CilekciGs** [Koelli91/windowshostsadblock#1]
Hello There, Since Internet Explorer is no longer supported on windows 11. Could you please update the script?

**Comment by koelle25** [comment]
Hi @CilekciGs,

as it was some time ago I created and used this script I just had a look into it again. It is in no way dependent on the Internet Explorer.

In fact, as the script is modifying the System's "Hosts"-File (and therefore intercepts DNS requests), it is completely autonomous and works system-wide - in Browsers as well as other Applications connecting to the internet.

But if you have the possibility I would consider using [Pi-hole](https://pi-hole.net/). This get's installed as your DNS (and if possible DHCP) service in your network, so it not only works on one PC but for the whole network, e.g. Phones and other devices, too.

**Comment by CilekciGs** [comment]
Thanks for your response @koelle25 , Invoke-WebRequest uses internet explorer by default. That's why it failed.
But with the new w11 update, The issue seems to be gone. Thanks for your attention.

**Comment by koelle25** [comment]
Oh okay.
Yeah, Invoke-Webrequest _should_ work without IE (afaik it is like `curl` for Linux).

Seems Microsoft forgot to write a different backing for it when they finally removed the IE.
But I'm glad they already fixed it!
